spring.application.name=Task-Manager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.locations=classpath:db/migration

spring.profiles.active=dev